- hosts: localhost
  gather_facts: false
  tasks:
    - set_fact:
        instance_name: "{{ ami_name }}_test"

    - name: get ec2 facts
      ec2_instance_info:
        filters:
          "tag:Name": "{{ instance_name }}"
      register: ec2

    # - debug:
    #     var: ec2

    - name: "destroy ec2 {{ instance_name }}"
      ec2_instance:
        region: us-east-1
        instance_ids: "{{ item.instance_id }}"
        state: absent
      loop: "{{ ec2.instances }}"
