- hosts: localhost
  gather_facts: false
  vars:
    keypair: "mackey"
    awsregion: "us-east-1"
    security_group: "default"
  tasks:
    - name: get ami-id
      ec2_ami_info:
        filters:
          name: "{{ ami_name }}"
      register: ami

    - set_fact:
        ami_id: "{{ ami['images'][0]['image_id'] }}"
        ami_root_device_name: "{{ ami['images'][0]['root_device_name'] }}"

    - name: create ec2s
      ec2_instance:
        region: "{{ awsregion }}"
        key_name: "{{ keypair }}"
        security_group: "{{ security_group }}"
        instance_type: t3.large
        image_id: "{{ ami_id }}"
        volumes:
          - device_name: "{{ ami_root_device_name }}"
            ebs:
              volume_type: gp3
              volume_size: 40
              delete_on_termination: true
        tags:
          Name: "{{ ami_name }}_test"
        network:
          assign_public_ip: true
      register: ec2info

    - debug:
        msg: "URL: https://{{ ec2info.instances[0].public_ip_address }} Password: {{ ec2info.instances[0].instance_id }}@AWS"
